export const vendorKPIs = [
  { label: 'Total Vendors', value: '156', trend: '+4%', trendUp: true, icon: 'vendors' },
  { label: 'Active Vendors', value: '142', trend: '+2%', trendUp: true, icon: 'active' },
  { label: 'Preferred Vendors', value: '38', trend: '+12%', trendUp: true, icon: 'preferred' },
  { label: 'Avg Vendor Rating', value: '4.7', trend: '+0.2', trendUp: true, icon: 'rating' },
];

export const vendorDistribution = [
  { name: 'IT Services', value: 45, color: '#3b82f6' },
  { name: 'Office Supplies', value: 30, color: '#10b981' },
  { name: 'Manufacturing', value: 25, color: '#f59e0b' },
  { name: 'Software', value: 40, color: '#8b5cf6' },
  { name: 'Logistics', value: 16, color: '#ef4444' },
];

export const vendorTableData = [
  {
    id: 'V-001',
    name: 'TechSupply Co.',
    email: 'contact@techsupply.com',
    category: 'IT Services',
    rating: 4.9,
    responseTime: '1.2h',
    ordersWon: 124,
    onTimeDelivery: 98,
    status: 'Preferred',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=TS',
  },
  {
    id: 'V-002',
    name: 'Global Office Pro',
    email: 'sales@globaloffice.com',
    category: 'Office Supplies',
    rating: 4.7,
    responseTime: '2.1h',
    ordersWon: 87,
    onTimeDelivery: 95,
    status: 'Active',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=GO',
  },
  {
    id: 'V-003',
    name: 'SwiftSourcing Ltd',
    email: 'info@swiftsourcing.com',
    category: 'Logistics',
    rating: 4.6,
    responseTime: '3.4h',
    ordersWon: 56,
    onTimeDelivery: 93,
    status: 'Active',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=SS',
  },
  {
    id: 'V-004',
    name: 'Apex Furnishings',
    email: 'support@apexfurnish.com',
    category: 'Manufacturing',
    rating: 4.4,
    responseTime: '4.0h',
    ordersWon: 42,
    onTimeDelivery: 89,
    status: 'Inactive',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=AF',
  },
  {
    id: 'V-005',
    name: 'CoreIT Solutions',
    email: 'hello@coreit.io',
    category: 'Software',
    rating: 4.2,
    responseTime: '5.5h',
    ordersWon: 31,
    onTimeDelivery: 86,
    status: 'Blacklisted',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=CI',
  },
  {
    id: 'V-006',
    name: 'Zenith Logistics',
    email: 'ops@zenithlog.com',
    category: 'Logistics',
    rating: 4.8,
    responseTime: '1.5h',
    ordersWon: 92,
    onTimeDelivery: 97,
    status: 'Preferred',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ZL',
  },
  {
    id: 'V-007',
    name: 'BuildRight Mfg',
    email: 'info@buildright.com',
    category: 'Manufacturing',
    rating: 4.5,
    responseTime: '2.8h',
    ordersWon: 64,
    onTimeDelivery: 91,
    status: 'Active',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=BR',
  },
  {
    id: 'V-008',
    name: 'PaperPlane Supplies',
    email: 'orders@paperplane.com',
    category: 'Office Supplies',
    rating: 4.3,
    responseTime: '3.2h',
    ordersWon: 48,
    onTimeDelivery: 94,
    status: 'Active',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=PP',
  },
];
